language: php

php:
    - "8.2"
    - "8.3"
    - "8.4"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y graphviz

before_script:
    - composer install

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - php: ["8.4"]
