language: php

php:
    - "5.3"
    - "5.4"
    - "5.5"
    - "hhvm"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y graphviz

before_script:
    - "curl -s http://getcomposer.org/installer | php"
    - "COMPOSER_ROOT_VERSION=dev-master php composer.phar install"

script: vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - php:
      - "hhvm"
